Первое и второе задание
FreeCourseJava/eebelyaev pull request #1
Opened 2022-06-27 20:48 UTC by eebelyaev

2022-06-28 06:32 UTC, blekkiw commented on src/lesson02/Main.java
> +        if (sign == amount >>> shift && sign != res >>> shift) res = 0;
Господи Иисусе. И ведь не поспоришь. Но лучше конечно, если это будет еще и читаться, пониматься без долгих вниканий со стороны других людей

2022-06-28 07:45 UTC, blekkiw requested changes

2022-06-28 07:45 UTC, blekkiw commented on src/lesson02/Main.java
> +        if (sign == amount >>> shift && sign != res >>> shift) res = 0;
Давай наверное все же уберем сдвиги и сделаем по-другому. Чтобы оно читалось, и было в рамках изучаемого материала. У некоторых может мозг потечь. Плюс помним, что всегда нужно писать выражения после ифа в фигурных скобках

2022-06-29 11:30 UTC, Aoascar reviewed
Круто!

2022-07-01 11:59 UTC, hyragano requested changes

2022-07-01 11:59 UTC, hyragano commented on src/lesson02/Main.java
> +        if (res > Integer.MAX_VALUE || res < Integer.MIN_VALUE) {
Тут можно без || попробуй сравнить сумму кастнутых с кастнутой суммой

2022-07-01 12:07 UTC, eebelyaev commented on src/lesson02/Main.java
> +        if (res > Integer.MAX_VALUE || res < Integer.MIN_VALUE) {
Зачем же ты подсказал как исправить, так неинтересно! ))

2022-07-01 12:07 UTC, hyragano requested changes

2022-07-01 12:07 UTC, hyragano commented on src/lesson02/Main.java
> +        if (res != (int) res) {
Тут разве пройдёт проверку?
я имел ввиду каст и сравнение лонгов

2022-07-01 12:12 UTC, eebelyaev commented on src/lesson02/Main.java
> +        if (res != (int) res) {
О какой проверке ты говоришь?
Код работает.

2022-07-01 12:19 UTC, hyragano commented on src/lesson02/Main.java
> +        if (res != (int) res) {
Он пройдёт поидее, но тут неочевидность есть, что  (int) res по-факту будет как (long) (int) res, лучше на такое поведение не завязываться если есть другие варианты

2022-07-01 12:31 UTC, eebelyaev commented on src/lesson02/Main.java
> +        if (res != (int) res) {
Сейчас переделаю. Но в чем неочевидность не понимаю: после "(int) res" отрежутся старшие 4 байта, после "(long) ((int) res)" добавятся 4 старших байта с нулями.

2022-07-01 12:44 UTC, hyragano commented on src/lesson02/Main.java
> +        if (res != (int) res) {
Я про читабельность, то есть тут сразу не поймёшь, что есть ещё повышение типа.

2022-07-01 13:16 UTC, hyragano approved these changes

2022-07-01 13:23 UTC, merged