Третье задание
FreeCourseJava/eebelyaev pull request #2
Opened 2022-07-01 13:42 UTC by eebelyaev

2022-07-02 14:30 UTC, hyragano requested changes

2022-07-02 14:30 UTC, hyragano commented on src/lesson03/Main.java
> +        int[] result = arrayInt.clone();
хитро, но молодец, что нашел

2022-07-02 14:30 UTC, hyragano commented on src/lesson03/Main.java
> +        for (int i = result.length; i > 1 ; i--) {
декременты в циклах использовать можно, но делай скидку на то, что твой код будет еще что-то читать ->  нужно писать максимально простой код

2022-07-02 14:30 UTC, hyragano commented on src/lesson03/Main.java
> +            middleIndex = beginIndex + (length >> 1);
Подход норм, но  c'mon, сдвиг в этой задаче не стоит юзать.

2022-07-02 14:30 UTC, hyragano commented on src/lesson03/TatarParser.java
> +public class TatarParser {
Кажись тебе всё, что у меня сейчас идет, будет не интересно явно еще месяца 4

2022-07-02 18:20 UTC, eebelyaev commented on src/lesson03/Main.java
> +            middleIndex = beginIndex + (length >> 1);
Ожидаю, что будет быстрее. Нет?

2022-07-02 20:57 UTC, eebelyaev commented on src/lesson03/TatarParser.java
> +public class TatarParser {
Отвечу в личку

2022-07-03 19:08 UTC, hyragano commented on src/lesson03/Main.java
> +            middleIndex = beginIndex + (length >> 1);
Будет быстрее, но не критичнно, т.е. тут можно выиграть ну пару тактов (и то не факт), но это совсем не то, что нужно

2022-07-07 14:23 UTC, merged